#!/usr/bin/env bash

FROM=/usr/local/share/legion-power-management/systemd
TO=/etc/systemd

link_unit() {
    if [[ -z "$1" ]]; then
        echo "Specify {system|user} units kind"
        exit 1
    fi
    if [[ -z "$2" ]]; then
        echo "Specify units list"
        exit 1
    fi
    for UNITFILE in $2; do
        ln -svf "${FROM}/$1/${UNITFILE}" "${TO}/$1/${UNITFILE}"
    done
}

install_unit_system() {
    if [[ -z "$1" ]]; then
        echo "Specify units list"
        exit 1
    fi
    for UNITFILE in $1; do
        systemctl enable "${UNITFILE}"
    done
}

install_unit_user() {
    if [[ -z "$1" ]]; then
        echo "Specify units list"
        exit 1
    fi
    for UNITFILE in $1; do
        systemctl enable --global "${UNITFILE}"
    done
}

link_unit system "\
    ideapad-extension-setup.service \
    legion-power-profile-balanced.service \
    legion-power-profile-performance.service \
    legion-power-profile-power-saver.service \
    legion-power-profiles-monitor.service \
    power-profile-performance-on-ac-plug.service"

link_unit user "ideapad-extension-setup.service"

systemctl daemon-reload

install_unit_system "\
    ideapad-extension-setup.service \
    legion-power-profile-balanced.service \
    legion-power-profile-performance.service \
    legion-power-profile-power-saver.service \
    legion-power-profiles-monitor.service \
    power-profile-performance-on-ac-plug.service"

install_unit_user "ideapad-extension-setup.service"
