#!/usr/bin/env bash

while true; do
    POWER_PROFILE_NEW_RAW=$(echo '\_SB_.PC00.LPCB.EC0_.SPMO' > /proc/acpi/call; tr -d '\0' < /proc/acpi/call | grep -e '^0x')
    case ${POWER_PROFILE_NEW_RAW} in
        0x0)
          # "Balanced"
          POWER_PROFILE_NEW='balanced'
        ;;
        0x1)
          # "Performance"
          POWER_PROFILE_NEW='performance'
        ;;
        0x2)
          # "Powersave"
          POWER_PROFILE_NEW='power-saver'
        ;;
        *)
          echo "Error getting HW power profile!"
        ;;
    esac
    POWER_PROFILE_OLD=$(powerprofilesctl get)
    if [[ ${POWER_PROFILE_NEW} != ${POWER_PROFILE_OLD} ]] && ( [[ ${POWER_PROFILE_NEW} = 'balanced' ]] || [[ ${POWER_PROFILE_NEW} = 'performance' ]] || [[ ${POWER_PROFILE_NEW} = 'power-saver' ]] ); then
        powerprofilesctl set "${POWER_PROFILE_NEW}"
    fi
    sleep 5
done
